### PR TITLE
Optimize the homepage

### PR DESCRIPTION
**Pull request by syndbg**
Addresses #17

### CODE REVIEW

**Comment by zedtux** [comment]
Thank you @syndbg for this ! :+1: 

Don't worry about Wercker, it's not a blocking point, I have to fix it but Shippable is the one I'm looking to.
I have to give it a try but the code is fine to me.
Feel free to ping me in case you don't see an update during the week.

**Comment by syndbg** [comment]
> Feel free to ping me in case you don't see an update during the week.
@zedtux  ping.

**Comment by zedtux** [comment]
@syndbg the pagination works great, but the counters of the tabs are then wrong.

**Comment by syndbg** [comment]
@zedtux I made the counters weird. They would increment on pagination which at that time when I was writing the PR... it might've made sense.

Anyway, now the counters display the total count of all / new / inactive formulas as they should.

**Comment by zedtux** [comment]
Counters are now fine but the pagination is no more working :s

**Comment by zedtux** [comment]
I can see a call to 'http://localhost:3000/?format=json&page=2' but the page doesn't refresh.

**Comment by syndbg** [comment]
@zedtux Page should not refresh. It's "SPA"-like. It updates the displayed items, but does not refresh the page.

Refreshing the page on each page completely kills the user experience.

**Comment by zedtux** [comment]
Sorry, I wasn't clear enough. It's not it should refresh the page, it should update the page. The first test I did, the page was updating on scrolling, but now it's no more the case.

**Comment by zedtux** [comment]
@syndbg do you have some news ? I'm waiting on this PR in order to build a new release for prod :)

**Comment by syndbg** [comment]
I was quite busy at that week (and more). I will look at the PR again after work. (EET here)

**Comment by zedtux** [comment]
Than you :) No worries I was just pinging you ;)

**Comment by syndbg** [comment]
@zedtux Fixed. Sorry for the delays.

**Comment by zedtux** [comment]
It working fine ! :+1:

**Pull request merged**
