### PR TITLE
API Documentation, description page

### LINKED ISSUE #10: Add an API description page
Following the implementation done in the issue #9, a page describing the API should be implemented with an entry in the menu.

Markdown will be used in order to render in HTML.

### PR DESCRIPTION
**Pull request by napcae**
I don't know if I missed anything from the API Documentation, but I couldn't see anything else from the sourcecode(reference 60df524f81a5ce).

closes #10

### CODE REVIEW

**Comment by zedtux** [comment]
Thank you @napcae ! The API is really simple, and you found it. I'll have a look and merge it.

**Comment by zedtux** [comment]
It's working just fine ! Great. LGTM.

**Comment by zedtux** [comment]
One last thing, there are conflicts. Can you please merge `master` and resolve them ?

**Comment by napcae** [comment]
I can't merge it since I don't have write access! 
screen shot 2015-11-08 at 22 43 50

Also, every build is failing since wrecker is integrated, [as far as I can tell](https://app.wercker.com/#applications/55fc060fee52f86b6d068b76) => #35 

Lastly, I don't know if its really necessary to use 3 CI platforms?

**Comment by zedtux** [comment]
Thank you @napcae.

> Lastly, I don't know if its really necessary to use 3 CI platforms?

This project is a playground for me. It's obviously useless :)

**Pull request merged**
