### PR TITLE
Update copyright year

### PR DESCRIPTION
**Pull request by z3t1**
Is it the right file? Sorry if it's wrong or you don't want to do that.

### CODE REVIEW

**Comment by zedtux** [comment]
Thank you @z3t1. Well I would even replace this line by something like

    Open source from 2013 until <current_year>

:)

**Comment by z3t1** [comment]
Then

<pre>Open source from 2013 until #{year}</pre>

**Comment by zedtux** [comment]
Exactly. Please change your PR and I will accept it

**Comment by z3t1** [comment]
Is it OK this way?

**Comment by zedtux** [comment]
@z3t1 not it's not working (See the failing build). You're calling `year` in the page but it's undefined. In this case, you want to use something like `Time.now.year`.

**Comment by z3t1** [comment]
Still not working. I know nothing about Slim. Should I import anything first?

**Comment by zedtux** [comment]
This time it's fine but there is a test which fails randomly ... I can accept the PR as it is now.

**Comment by zedtux** [comment]
@z3t1 your changes are in production :)

**Pull request merged**
